

# DEVO RICORDARMI CHE NELLA FASE Dello SVILLUPPO DEVO CAMBIARE IL VALORE DELLA VARIABILE =dev


spring.datasource.url=jdbc:postgresql://localhost:5432/proggetto_finale_f_s?currentSchema=public
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:34451}
spring.jpa.hibernate.ddl-auto=update

# Logging (Solo in sviluppo)
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG