



# DEVO RICORDARMI CHE NELLA FASE DI PRODUZIONE DEVO IMPOSTARE IL VALORE DELLA VARIABILE =prod




spring.profiles.disable=prod

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# Logging (Livello di logging ridotto per la produzione)
logging.level.org.springframework.security=INFO
logging.level.root=WARN